# Generated by Django 4.2.4 on 2023-08-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
